trailingComma: 'es5'
semi: true
singleQuote: true
pluginSearchDirs: false
plugins:
  - '@shopify/prettier-plugin-liquid'
  - prettier-plugin-tailwindcss
overrides:
  - files: '*.html'
    options:
      printWidth: 200 # This will prevent wrapping of the tags’ attributes.
      singleQuote: false
      parser: 'liquid-html'
