# For some reason overriding in the root config file does not work well with plugins.
# https://prettier.io/docs/en/configuration.html#configuration-overrides
# Therefore as of now we have a separate config for the frontend.
trailingComma: 'es5'
semi: true
singleQuote: true
proseWrap: always
# We have to configure plugins explicitly in this order
# according to https://github.com/tailwindlabs/prettier-plugin-tailwindcss/#compatibility-with-other-prettier-plugins
pluginSearchDirs: false
plugins:
  - '@shopify/prettier-plugin-liquid'
  - prettier-plugin-tailwindcss
overrides:
  - files: '*.html'
    options:
      printWidth: 200 # This will prevent wrapping of the tags’ attributes.
      singleQuote: false
      parser: 'liquid-html'
