root: true
env:
  node: true
  es2022: true
parserOptions:
  sourceType: module
plugins:
  - import
  - header
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - prettier
rules:
  'header/header':
    - error
    - block
    - ['!', ' * sri sri guru gaurangau jayatah', ' ']
    - 2
  import/extensions:
    - error
    - ignorePackages
  import/no-commonjs:
    - error
    - allowConditionalRequire: false
overrides:
  - files: '**/*.spec.js'
    plugins: [jest]
    extends:
      - plugin:jest/recommended
      - plugin:jest/style
