trailingComma: 'es5'
semi: true
singleQuote: true
jsdocUseInlineCommentForASingleTagBlock: true
jsdocPrintWidth: 120 # Needed due to https://github.com/homer0/packages/issues/59
jsdocTagsOrder:
  - type
  - typedef
  - callback
  - function
  - method
  - class
  - file
  - constant
  - description
  - classdesc
  - example
  - template
  - param
  - property
  - returns
  - augments
  - extends
  - throws
  - yields
  - fires
  - listens
  - async
  - abstract
  - override
  - private
  - protected
  - public
  - access
  - desprecated
  - author
  - version
  - since
  - member
  - memberof
  - category
  - external
  - see
  - other
  - todo
overrides:
  - files: '*.html'
    options:
      printWidth: 200 # This will prevent wrapping of the tags’ attributes.
      singleQuote: false
      parser: 'liquid-html'
