# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Setup Firebase Tools
description: Setup Firebase CLI and GAC
inputs:
  service-account:
    description: A service account to initialize GOOGLE_APPLICATION_CREDENTIALS
runs:
  using: composite
  steps:
    - run: curl -sL firebase.tools | analytics=false bash
      shell: bash
    - run:
        echo "GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/service-account.json" >> $GITHUB_ENV
        echo $SERVICE_ACCOUNT > $GOOGLE_APPLICATION_CREDENTIALS
      shell: bash
      if: inputs.service-account
      env:
        SERVICE_ACCOUNT: ${{ inputs.service-account }}
