name: Deployment
on:
  workflow_call:
    inputs:
      environment:
        description: Environment to deploy to
        required: true
        type: string
      preview:
        description: Whether to deploy to a preview channel
        required: false
        default: false
        type: boolean

concurrency:
  group: ${{ inputs.environment }}_deployment
  cancel-in-progress: true
defaults:
  run:
    # To ensure pipefail (https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference)
    # See also https://stackoverflow.com/a/19804002
    shell: bash
jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deploy-production.outputs.url || steps.deploy-preview.outputs.url }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: frontend/package.json
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - run: npm ci
        working-directory: frontend

      - run: npm run build
        name: Build frontend
        working-directory: frontend
        env:
          ALGOLIA_APPLICATION_ID: ${{ vars.ALGOLIA_APPLICATION_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_INDEX_AUDIOS: ${{ vars.ALGOLIA_INDEX_AUDIOS }}
          ALGOLIA_INDEX_MEMORIES: ${{ vars.ALGOLIA_INDEX_MEMORIES}}
          STORAGE_BASE_URL: ${{ vars.STORAGE_BASE_URL}}
          DONATION_URL: ${{ vars.DONATION_URL}}
          FEEDBACK_FORM_AUDIOS: ${{ vars.FEEDBACK_FORM_AUDIOS}}
          FEEDBACK_FORM_MEMORIES: ${{ vars.FEEDBACK_FORM_MEMORIES }}
          DIRECTUS_URL: ${{ vars.DIRECTUS_URL }}
          DIRECTUS_STATIC_TOKEN: ${{ secrets.DIRECTUS_STATIC_TOKEN }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

      - run: npm i -g firebase-tools

      - run: echo $SERVICE_ACCOUNT > ${{ runner.temp }}/service-account.json
        name: Setup Google Service Account
        env:
          SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Deploy to production
        run: |
          firebase deploy --only hosting --project ${{ vars.GCP_PROJECT_ID }} --force --non-interactive

          # Inspired by https://superuser.com/a/943466 and https://stackoverflow.com/a/74998363
          firebase hosting:sites:list --json --project ${{ vars.GCP_PROJECT_ID }} \
          | jq '.result.sites[] | select(.type == "DEFAULT_SITE") | .defaultUrl' --raw-output \
          | (echo -n "url=" && cat) >> $GITHUB_OUTPUT
        id: deploy-production
        if: ${{ ! inputs.preview }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/service-account.json

      - name: Deploy to a preview channel
        run: |
          firebase hosting:channel:deploy ${{ github.head_ref }} --json --project ${{ vars.GCP_PROJECT_ID }} \
          | jq '.result."${{ vars.GCP_PROJECT_ID }}".url' --raw-output \
          | (echo -n "url=" && cat) >> $GITHUB_OUTPUT
        id: deploy-preview
        if: ${{ inputs.preview }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/service-account.json

      - uses: algolia/setup-algolia-cli@v1.1.0
        with:
          version: 1.4.2 # latest at the moment. Need at least 1.3.0 to deal with the config

      - name: Update Algolia index
        # Mimicking the behaviour of replace-all-objects: https://www.algolia.com/doc/api-reference/api-methods/replace-all-objects/
        run: |
          algolia indices config import $TEMP_INDEX -F algolia/audios.json --scope settings,synonyms,rules --confirm

          # https://www.algolia.com/doc/tools/cli/examples/recipes/#import-from-a-json-file
          jq -c '.[]?' frontend/dist/.search/audios.json | algolia objects import $TEMP_INDEX -F -

          algolia indices move $TEMP_INDEX $INDEX --confirm
        env:
          ALGOLIA_CLI_TELEMETRY: 0
          # CLI uses these two env variable for authentication: https://github.com/algolia/setup-algolia-cli/issues/4#issuecomment-1465172597
          ALGOLIA_APPLICATION_ID: ${{ vars.ALGOLIA_APPLICATION_ID }}
          ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
          INDEX: ${{ vars.ALGOLIA_INDEX_AUDIOS }}
          TEMP_INDEX: ${{ vars.ALGOLIA_INDEX_AUDIOS }}_tmp
