# We have to use this intermediate workflow because the `repository_dispatch`
# workflow runs in the default branch only, which violates the production environment
# protection rule.
# Source of inspiration: https://github.com/orgs/community/discussions/24657#discussioncomment-3244904
name: Deployment Webhook
on:
  repository_dispatch:
    types:
      - production_deployment

jobs:
  initiate:
    name: Initiate deployment
    runs-on: ubuntu-latest

    steps:
      - name: Debounce
        uses: zachary95/github-actions-debounce@v0.1.0
        with:
          wait: 120

      - name: Invoke the deployment workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: deployment.yaml
          ref: production
