name: Deployment
on:
  push:
    branches:
      - production
      - test
  workflow_dispatch:

concurrency:
  group: deployment-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  download-audio-data:
    name: Download audios data
    uses: ./.github/workflows/download-audios-data.yaml
    secrets: inherit

  deployment:
    runs-on: ubuntu-latest
    needs: download-audio-data
    environment: ${{ github.ref_name }}

    steps:
      # 1. Updating Algolia index

      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.download-audio-data.outputs.artifact-name }}
          path: ${{ runner.temp }}

      # Pinning the commit SHA because this action does not maintain semver refs yet: https://github.com/algolia/setup-algolia-cli/issues/1#issuecomment-1465535303
      - uses: algolia/setup-algolia-cli@0af6968e098cc0526e22871fe46abe9a34e43e8d
      # Mimicing the behaviour of replace-all-objects: https://www.algolia.com/doc/api-reference/api-methods/replace-all-objects/
      - run: |
          algolia indices copy $INDEX $TEMP_INDEX --scope settings,synonyms,rules --confirm

          # https://www.algolia.com/doc/tools/cli/examples/recipes/#import-from-a-json-file
          jq -c '.[]' $AUDIOS_DATA_PATH | algolia objects import $TEMP_INDEX -F -

          algolia indices move $TEMP_INDEX $INDEX --confirm
        env:
          ALGOLIA_CLI_TELEMETRY: 0
          # CLI uses these two env variable for authentication: https://github.com/algolia/setup-algolia-cli/issues/4#issuecomment-1465172597
          ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
          INDEX: ${{ vars.ALGOLIA_INDEX_AUDIOS }}
          TEMP_INDEX: ${{ vars.ALGOLIA_INDEX_AUDIOS }}_tmp
          AUDIOS_DATA_PATH: ${{ runner.temp }}/audios.json
