name: Deployment
on:
  push:
    branches:
      - production
      - test
  workflow_dispatch:

concurrency:
  group: deployment-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  download-audio-data:
    name: Download audios data
    uses: ./.github/workflows/download-audios-data.yaml
    secrets: inherit

  deployment:
    runs-on: ubuntu-latest
    needs: download-audio-data
    environment: ${{ github.ref_name }}

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.download-audio-data.outputs.artifact-name }}
          path: ${{ runner.temp }}

      - uses: algolia/setup-algolia-cli@0af6968e098cc0526e22871fe46abe9a34e43e8d
      - run: |
          algolia indices copy ${{ vars.ALGOLIA_AUDIOS_INDEX }} $TEMP_INDEX --scope settings,synonyms,rules --confirm

          # https://www.algolia.com/doc/tools/cli/examples/recipes/#import-from-a-json-file
          jq -c '.[]' $AUDIOS_DATA_PATH | algolia objects import $TEMP_INDEX -F -

          algolia indices move $TEMP_INDEX ${{ vars.ALGOLIA_AUDIOS_INDEX }} --confirm
        env:
          ALGOLIA_CLI_TELEMETRY: 0
          ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
          TEMP_INDEX: ${{ vars.ALGOLIA_AUDIOS_INDEX }}_tmp
          AUDIOS_DATA_PATH: ${{ runner.temp }}/audios.json
