name: Download audios data
on:
  workflow_call:
    outputs:
      artifact-name:
        value: ${{ jobs.download.outputs.artifact-name }}
jobs:
  download:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ env.ARTIFACT_NAME }}
    env:
      DATA_FILE_PATH: audios.json
      ARTIFACT_NAME: audios-data
    steps:
      - run: echo $SERVICE_ACCOUNT > service-account.json
        env:
          SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - run: curl -sL firebase.tools | analytics=false bash
      - run: firebase database:get /audio/records --output $DATA_FILE_PATH --project ${{ vars.GCP_PROJECT_ID }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: service-account.json
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.DATA_FILE_PATH }}
          if-no-files-found: error
