#
# sri sri guru gaurangau jayatah
#

name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  changes:
    name: Detect changes in sub-projects
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend == 'true' || steps.filter.outputs.workflows == 'true' }}
      functions: ${{ steps.filter.outputs.functions == 'true' || steps.filter.outputs.workflows == 'true' }}
    steps:
      # Checkout to use filters from file
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: .github/path-filters.yaml

  # Job id should match the folder name because it's used in the expressions
  frontend:
    name: Build and test frontend
    runs-on: ubuntu-latest
    needs: changes
    defaults:
      run:
        working-directory: ${{ github.job }}

    # It is not possible to use `github.job` inside `if` expression
    # Comparing to string, because the job output is a strings, not boolean
    if: needs.changes.outputs.frontend == 'true'
    steps:
      - uses: actions/checkout@v4

      # Setting environment variables which depend on the runner, cannot set in jobs.env: https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability
      - run: echo "AUDIOS_DATA_PATH=$RUNNER_TEMP/audios.json" >> $GITHUB_ENV
      - run: echo "GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/service-account.json" >> $GITHUB_ENV

      - run: echo $SERVICE_ACCOUNT > $GOOGLE_APPLICATION_CREDENTIALS
        env:
          SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - run: curl -sL firebase.tools | analytics=false bash
      # Downloading audios data file from Firebase RTDB
      - run: firebase database:get /audio/records --output $AUDIOS_DATA_PATH --project ${{ vars.GCP_PROJECT_ID }}

      - uses: actions/setup-node@v3
        with:
          node-version-file: ${{ github.job }}/package.json
          cache: npm
          cache-dependency-path: ${{ github.job }}/package-lock.json

      - run: npm ci
      - run: npm run lint
      - run: npm run check-js-typing
      - run: npm run build
        env:
          ALGOLIA_APPLICATION_ID: ${{ vars.ALGOLIA_APPLICATION_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_INDEX_AUDIOS: ${{ vars.ALGOLIA_INDEX_AUDIOS }}
          ALGOLIA_INDEX_MEMORIES: ${{ vars.ALGOLIA_INDEX_MEMORIES}}
          STORAGE_BASE_URL: ${{ vars.STORAGE_BASE_URL}}
          DONATION_URL: ${{ vars.DONATION_URL}}
          FEEDBACK_FORM_AUDIOS: ${{ vars.FEEDBACK_FORM_AUDIOS}}
          FEEDBACK_FORM_MEMORIES: ${{ vars.FEEDBACK_FORM_MEMORIES}}
          DIRECTUS_URL: ${{ vars.DIRECTUS_URL }}
          DIRECTUS_STATIC_TOKEN: ${{ secrets.DIRECTUS_STATIC_TOKEN }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

      - run: npm test --if-present
      - run: npx prettier --check .

  # Job id should match the folder name because it's used in the expressions
  functions:
    name: Lint and test functions
    runs-on: ubuntu-latest
    needs: changes
    defaults:
      run:
        working-directory: ${{ github.job }}
    # It is not possible to use `github.job` inside `if` expression
    # Comparing to string, because the job output is a strings, not boolean
    if: needs.changes.outputs.functions == 'true'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version-file: ${{ github.job }}/package.json
          cache: npm
          cache-dependency-path: ${{ github.job }}/package-lock.json

      - run: npm ci
      - run: npm run lint
      - run: npm run check-js-typing
      - run: npm test -- --passWithNoTests
      - run: npx prettier --check .

  check:
    name: Summary Check
    if: always()
    needs:
      - frontend
      - functions
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')

  deployment:
    name: Deploy to Firebase Hosting
    uses: ./.github/workflows/deployment.yaml
    with:
      environment: preview
    secrets: inherit
    if: contains( github.event.pull_request.labels.*.name, 'preview')
