#
# sri sri guru gaurangau jayatah
#

name: CI
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  changes:
    name: Detect changes in sub-projects
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend == 'true' || steps.filter.outputs.workflows == 'true' }}
      functions: ${{ steps.filter.outputs.functions == 'true' || steps.filter.outputs.workflows == 'true' }}
    steps:
      # Checkout to use filters from file
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: .github/path-filters.yaml

  # Job id should match the folder name because it's used in the expressions
  frontend:
    name: Build and test frontend
    runs-on: ubuntu-latest
    needs: changes
    defaults:
      run:
        working-directory: ${{ github.job }}

    # It is not possible to use `github.job` inside `if` expression
    # Comparing to string, because the job output is a strings, not boolean
    if: needs.changes.outputs.frontend == 'true'
    env:
      GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v3

      # Setting environment variables which depend on the runner, cannot set in jobs.env: https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability
      - run: echo "AUDIOS_DATA_PATH=$RUNNER_TEMP/audios.json" >> $GITHUB_ENV
      - run: echo "GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/service-account.json" >> $GITHUB_ENV

      - run: echo $SERVICE_ACCOUNT > $GOOGLE_APPLICATION_CREDENTIALS
        env:
          SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - run: curl -sL firebase.tools | analytics=false bash
      # Downloading audios data file from Firebase RTDB
      - run: firebase database:get /audio/records --output $AUDIOS_DATA_PATH --project $GCP_PROJECT_ID

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: ${{ github.job }}/package-lock.json

      - run: npm ci
      - run: npm run lint
      - run: npm run check-js-typing
      - run: npm run build
        env:
          ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_INDEX_AUDIOS: ${{ vars.ALGOLIA_INDEX_AUDIOS }}
          ALGOLIA_INDEX_MEMORIES: ${{ vars.ALGOLIA_INDEX_MEMORIES}}
          STORAGE_BASE_URL: ${{ vars.STORAGE_BASE_URL}}
          DONATION_URL: ${{ vars.DONATION_URL}}
          FEEDBACK_FORM_AUDIOS: ${{ vars.FEEDBACK_FORM_AUDIOS}}
          FEEDBACK_FORM_MEMORIES: ${{ vars.FEEDBACK_FORM_MEMORIES}}
          DIRECTUS_URL: ${{ vars.DIRECTUS_URL }}
          DIRECTUS_STATIC_TOKEN: ${{ secrets.DIRECTUS_STATIC_TOKEN }}

      - run: npm test --if-present
      - run: npx prettier --check .
      - run: tar -cvf ${{ runner.temp }}/dist.tar dist
      - name: Upload dist folder for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: ${{ runner.temp }}/dist.tar

  # Job id should match the folder name because it's used in the expressions
  functions:
    name: Lint and test functions
    runs-on: ubuntu-latest
    needs: changes
    defaults:
      run:
        working-directory: ${{ github.job }}
    # It is not possible to use `github.job` inside `if` expression
    # Comparing to string, because the job output is a strings, not boolean
    if: needs.changes.outputs.functions == 'true'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: ${{ github.job }}/package-lock.json

      - run: npm ci
      - run: npm run lint
      - run: npm run check-js-typing
      - run: npm test -- --passWithNoTests
      - run: npx prettier --check .

  deployment:
    name: Deploy to Firebase Hosting Preview Channel
    runs-on: ubuntu-latest
    needs: frontend
    if: contains( github.event.pull_request.labels.*.name, 'preview')
    environment:
      name: preview-${{ github.head_ref }}
      url: ${{ steps.deploy.outputs.channel-url }}
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact from build job
        id: download
        uses: actions/download-artifact@v3
        with:
          name: frontend
          path: ${{ runner.temp }}

      - run: tar -xvf ${{steps.download.outputs.download-path}}/dist.tar -C frontend
      - run: echo $SERVICE_ACCOUNT > ${{ runner.temp }}/service-account.json
        env:
          SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - run: curl -sL firebase.tools | analytics=false bash
      - name: Deploy
        # Inspired by https://superuser.com/a/943466 and https://stackoverflow.com/a/74998363
        run: |
          set -o pipefail # https://stackoverflow.com/a/19804002
          firebase hosting:channel:deploy ${{ github.head_ref }} --json --project ${{ vars.GCP_PROJECT_ID }} |\
          jq '.result."${{ vars.GCP_PROJECT_ID }}".url' --raw-output |\
          (echo -n "channel-url=" && cat) >> $GITHUB_OUTPUT
        id: deploy
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/service-account.json
